spring:
  application:
    name: junifydb-spring-boot-test
  
  jpa:
    database-platform: org.junify.db.adapter.jpa.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    jpa:
      repositories:
        enabled: true

junifydb:
  enabled: true
  engine: IN_MEMORY
  data-dir: ./data/junifydb
  auto-flush: true
  enable-server: false
  port: 8080

logging:
  level:
    org.junify.db: DEBUG
    org.springframework: INFO